export const Interest = {
    CROWDFUNDING_SUPPORT: "CROWDFUNDING_SUPPORT",
    MARKETING_PRELAUNCH: "MARKETING_PRELAUNCH",
    STORY_BRAND_PITCH: "STORY_BRAND_PITCH",
    BIZ_MODEL_FINANCE: "BIZ_MODEL_FINANCE",
    EQUITY_CROWDFUNDING: "EQUITY_CROWDFUNDING",
    OTHER: "OTHER",
};

export const Readiness = {
    EXPLORING: "EXPLORING",
    WITHIN_3_MONTHS: "WITHIN_3_MONTHS",
    THREE_TO_SIX_MONTHS: "THREE_TO_SIX_MONTHS",
    SIX_TO_TWELVE_MONTHS: "SIX_TO_TWELVE_MONTHS",
};

export const NextStep = {
    BOOK_CALL: "BOOK_CALL",
    SEND_INFO: "SEND_INFO",
};
